### ISSUE TITLE
Make the repository compliant to the open source standards

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#1]
## Proposed solution
We need to have a repository that follows all the [community standards](https://github.com/blockful-io/external-resolver/community) as an open source project which means:

- [x] Add repository description
- [x] Add `README.md`
- [x] Implement code of conduct
- [x] Implement `CONTRIBUITING.md`
- [x] Add license file
- [x] Implement security policy
- [x] Implement pull request template 
- [x] Set code owners
- [x] Create milestones and subtasks
