### ISSUE TITLE
Create architecture diagrams

### ISSUE THREAD

**Issue by pikonha** [blockful-io/external-resolver#2]
### Describe the Feature Request

To start building the project, it will be needed to plan all the flow of interactions between each part. So, the ideia of this task is to create some diagrams that represents the code structure, architecture and flow.

### Describe Preferred Solution

To achieve the mentioned goal, the task will be broke into 4 pieces:
- [x] Project architecture for Layer 2 communication
- [x] Project architecture for Database communication
- [x] Interaction flow between project parts for Layer 2 communication
- [x] Interaction flow between project parts for Database communication
